#!/usr/bin/env perl
use strict;
use warnings;

use Test::NaiveStubs;

my $module = shift || die "Usage: perl $0 Some::Module\n";

eval "require $module";
die "Can't require $module: $@" if $@;

my $t = Test::NaiveStubs->new( module => $module );

$t->create_test;
